# Header
# 菜单项的相关配置
menu:
  home: /
  archives: /archives
  tags: /tags
  about: /about

#  Content
#  显示内容配置
#  excerpt_link: 阅读全文  #设置查看全文的按钮显示文本
#  fancybox: ture  #是否开启弹出层效果
 
#  Sidebar
#  侧边栏配置
#  sidebar: right #侧边栏展示的方向
#  widgets:  #侧边栏添加的组件配置
#  - categoty  #显示分类
#  - tag  #显示标签
#  - tagcloud  #显示标签云
#  - archive  #显示归档
#  - recent_posts  #显示最近发布
# highlight.js
highlight_theme: tomorrow-night